server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yanolja?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

jwt:
  secret: your-secret-key-here
  access-token-expiration: 900000 # 15분 (밀리초)
  refresh-token-expiration: 1209600000 # 2주 (밀리초)
  header: Authorization
  prefix: "Bearer "

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
